//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ftims.Pai.Client.Services.Project {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/Ftims.Pai.Service.TimesheetService.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ftims.Pai.Client.Services.Project.ProjectWithDetails))]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectWithDetails", Namespace="http://schemas.datacontract.org/2004/07/Ftims.Pai.Service.TimesheetService.DTO")]
    [System.SerializableAttribute()]
    public partial class ProjectWithDetails : Ftims.Pai.Client.Services.Project.Project {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ftims.Pai.Client.Services.Project.Employee ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ftims.Pai.Client.Services.Project.Employee Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/Ftims.Pai.Service.TimesheetService.DTO")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateProject", Namespace="http://schemas.datacontract.org/2004/07/Ftims.Pai.Service.TimesheetService.DTO")]
    [System.SerializableAttribute()]
    public partial class CreateProject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Project.IProjectService")]
    public interface IProjectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Find", ReplyAction="http://tempuri.org/IProjectService/FindResponse")]
        Ftims.Pai.Client.Services.Project.Project[] Find(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Find", ReplyAction="http://tempuri.org/IProjectService/FindResponse")]
        System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project[]> FindAsync(string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Get", ReplyAction="http://tempuri.org/IProjectService/GetResponse")]
        Ftims.Pai.Client.Services.Project.Project Get(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Get", ReplyAction="http://tempuri.org/IProjectService/GetResponse")]
        System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project> GetAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/GetDetails", ReplyAction="http://tempuri.org/IProjectService/GetDetailsResponse")]
        Ftims.Pai.Client.Services.Project.ProjectWithDetails GetDetails(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/GetDetails", ReplyAction="http://tempuri.org/IProjectService/GetDetailsResponse")]
        System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.ProjectWithDetails> GetDetailsAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/GetAll", ReplyAction="http://tempuri.org/IProjectService/GetAllResponse")]
        Ftims.Pai.Client.Services.Project.Project[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/GetAll", ReplyAction="http://tempuri.org/IProjectService/GetAllResponse")]
        System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Create", ReplyAction="http://tempuri.org/IProjectService/CreateResponse")]
        Ftims.Pai.Client.Services.Project.Project Create(Ftims.Pai.Client.Services.Project.CreateProject project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Create", ReplyAction="http://tempuri.org/IProjectService/CreateResponse")]
        System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project> CreateAsync(Ftims.Pai.Client.Services.Project.CreateProject project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Update", ReplyAction="http://tempuri.org/IProjectService/UpdateResponse")]
        void Update(string id, Ftims.Pai.Client.Services.Project.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Update", ReplyAction="http://tempuri.org/IProjectService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string id, Ftims.Pai.Client.Services.Project.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Delete", ReplyAction="http://tempuri.org/IProjectService/DeleteResponse")]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectService/Delete", ReplyAction="http://tempuri.org/IProjectService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectServiceChannel : Ftims.Pai.Client.Services.Project.IProjectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServiceClient : System.ServiceModel.ClientBase<Ftims.Pai.Client.Services.Project.IProjectService>, Ftims.Pai.Client.Services.Project.IProjectService {
        
        public ProjectServiceClient() {
        }
        
        public ProjectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ftims.Pai.Client.Services.Project.Project[] Find(string expression) {
            return base.Channel.Find(expression);
        }
        
        public System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project[]> FindAsync(string expression) {
            return base.Channel.FindAsync(expression);
        }
        
        public Ftims.Pai.Client.Services.Project.Project Get(string id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project> GetAsync(string id) {
            return base.Channel.GetAsync(id);
        }
        
        public Ftims.Pai.Client.Services.Project.ProjectWithDetails GetDetails(string id) {
            return base.Channel.GetDetails(id);
        }
        
        public System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.ProjectWithDetails> GetDetailsAsync(string id) {
            return base.Channel.GetDetailsAsync(id);
        }
        
        public Ftims.Pai.Client.Services.Project.Project[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Ftims.Pai.Client.Services.Project.Project Create(Ftims.Pai.Client.Services.Project.CreateProject project) {
            return base.Channel.Create(project);
        }
        
        public System.Threading.Tasks.Task<Ftims.Pai.Client.Services.Project.Project> CreateAsync(Ftims.Pai.Client.Services.Project.CreateProject project) {
            return base.Channel.CreateAsync(project);
        }
        
        public void Update(string id, Ftims.Pai.Client.Services.Project.Project project) {
            base.Channel.Update(id, project);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string id, Ftims.Pai.Client.Services.Project.Project project) {
            return base.Channel.UpdateAsync(id, project);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
